services:
  backend:
    build: .
    ports:
      - "8000:8000"
    container_name: jwt-fastapi-backend
    environment:
      JWT_SECRET_KEY: "${JWT_SECRET_KEY:?JWT_SECRET_KEY is required}"
      JWT_ADMIN_USERNAME: "${JWT_ADMIN_USERNAME:-admin}"
      JWT_ADMIN_PASSWORD: "${JWT_ADMIN_PASSWORD:-admin123}"
